---
- name: Install apt-transport-https (see https://docs.docker.com/engine/installation/linux/ubuntu/#recommended-extra-packages-for-trusty-1404)
  apt:
     name: apt-transport-https
     state: latest
  sudo: yes

- name: Install ca-certificates (see https://docs.docker.com/engine/installation/linux/ubuntu/#recommended-extra-packages-for-trusty-1404)
  apt:
     name: ca-certificates
     state: latest
  sudo: yes

- name: Install software-properties-common (see https://docs.docker.com/engine/installation/linux/ubuntu/#recommended-extra-packages-for-trusty-1404)
  apt:
     name: software-properties-common
     state: latest
  sudo: yes

- name: Add Docker apt key
  apt_key:
     url: https://download.docker.com/linux/ubuntu/gpg
     id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
     state: present
  register: add_repository_key
  ignore_errors: true

- name: Ensure curl is present (on older systems without SNI).
  apt:
     name: curl
     state: latest
  sudo: yes
  when: add_repository_key|failed

- name: Add Docker apt key (alternative for older systems without SNI).
  shell: "curl -sSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
  args:
      warn: no
  when: add_repository_key|failed

- name: Add docker apt repo
  apt_repository:
     repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_lsb.codename}} stable"
     update_cache: yes
  sudo: yes

- name: Install Docker apt package
  apt:
     pkg: docker-ce
     state: latest
     update_cache: yes
  sudo: yes

- name: Ensure Docker service is installed and restarted
  service:
     name: docker
     state: restarted
     enabled: yes
  sudo: yes

- name: Pull NGINX Docker Image
  shell: "sudo docker pull nginx"  

- name: Setup directory HTML and Write Indexhtml content
  shell: |
     rm -rf ~/docker-nginx/html 
     mkdir -p ~/docker-nginx/html
  ignore_errors: yes

- name: Ansible copy file to remote server
  copy:
      src: /Users/vishydarshy/Work/software/index.html
      dest: ~/docker-nginx/html/ 
 
- name: Check for containers that actually exist
  shell: sudo docker rm $(sudo docker ps -a -q) 
  register: found_containers
  ignore_errors: yes 

- name: run Docker nginx NEWLA  Image 80 port
  shell: "sudo docker run --name docker-nginx -p 80:80 -d -v ~/docker-nginx/html:/usr/share/nginx/html nginx"


